/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.eth.validation;

import alma.Control.datamodel.meta.eth.MandC;

import org.eclipse.emf.ecore.resource.Resource;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.eth.Control}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ControlValidator {
	boolean validate();

	boolean validateMac(MandC value);
	boolean validateAux2(Resource value);
	boolean validateToInfoControlEth(MandC value);

	boolean validateInfoControlEth(MandC value);
}
