/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.amb.validation;

import alma.Control.datamodel.meta.amb.MandC;

import alma.Control.datamodel.meta.base.BaseFactory;
import alma.Control.datamodel.meta.base.Table;
import alma.Control.datamodel.meta.base.Util;

import alma.Control.datamodel.meta.base.impl.BaseFactoryImpl;

import org.eclipse.emf.ecore.resource.Resource;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.amb.Control}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ControlValidator {
	boolean validate();

	boolean validateMac(MandC value);
	boolean validateTmp(BaseFactory value);
	boolean validateTmp2(BaseFactoryImpl value);
	boolean validateAux2(Resource value);
	boolean validateToWorldToDataColumns(Table value);

	boolean validateToInfoControlSheet(MandC value);

	boolean validateWorldToDataColumns(Table value);
	boolean validateGetInfoControlSheet(MandC value);
	boolean validateToNormalizeNumber(Util value);
}
