/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.amb.validation;

import alma.Control.datamodel.meta.amb.Archive;
import alma.Control.datamodel.meta.amb.Control;
import alma.Control.datamodel.meta.amb.GenericMonitorPoints;
import alma.Control.datamodel.meta.amb.Main;
import alma.Control.datamodel.meta.amb.Monitor;

import alma.Control.datamodel.meta.base.ControlPoint;
import alma.Control.datamodel.meta.base.MainBase;
import alma.Control.datamodel.meta.base.MonitorPoint;
import alma.Control.datamodel.meta.base.Note;
import alma.Control.datamodel.meta.base.SpreadsheetParser;
import alma.Control.datamodel.meta.base.SpreadsheetValidator;
import alma.Control.datamodel.meta.base.Table;
import alma.Control.datamodel.meta.base.Util;

import alma.Control.datamodel.meta.base.impl.BaseFactoryImpl;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.amb.DeviceModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeviceModelValidator {
	boolean validate();

	boolean validateTmp(BaseFactoryImpl value);
	boolean validateToAddCP(ControlPoint value);
	boolean validateToNoteFromMain(Note value);

	boolean validateGetNoteFromMain(Note value);
	boolean validateToAddMP(MonitorPoint value);
	boolean validateToInfoMain(MainBase value);

	boolean validateToCPfromControl(Control value);

	boolean validateToInfoFromMainSheet(Main value);

	boolean validateToMPfromMonitor(Monitor value);

	boolean validateToDataFromSpread(Table value);

	boolean validateToAPfromArchive(Archive value);

	boolean validateToInstallEndGeneration(Util value);

	boolean validateToSpreadsheetFrom(SpreadsheetParser value);

	boolean validateGetInfoMain(MainBase value);
	boolean validateGetCPfromControl(Control value);
	boolean validateGetInfoFromMainSheet(Main value);
	boolean validateGetMPfromMonitor(Monitor value);
	boolean validateGetDataFromSpread(Table value);
	boolean validateGetAPfromArchive(Archive value);
	boolean validateToinstallEndGeneration(Util value);
	boolean validateGetFromSpreadsheet(SpreadsheetParser value);
	boolean validateToValidateSpreadsheet(SpreadsheetValidator value);
	boolean validateToGenericMP(GenericMonitorPoints value);

	boolean validateGetGenericMP(GenericMonitorPoints value);
}
