/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.amb.validation;

import alma.Control.datamodel.meta.base.SpreadsheetParser;
import alma.Control.datamodel.meta.base.SpreadsheetValidator;
import alma.Control.datamodel.meta.base.Util;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.amb.GenericMonitorPoints}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GenericMonitorPointsValidator {
	boolean validate();

	boolean validateNewSpreadsheet(String[][][] value);
	boolean validateDeviceName(String value);
	boolean validateDirLocation(String value);
	boolean validateToGetSpreadsheet(SpreadsheetParser value);

	boolean validateGetTheSpreadsheet(SpreadsheetParser value);
	boolean validateToValidateTheSpreadsheet(SpreadsheetValidator value);
	boolean validateToInstallDir(Util value);
}
