/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.amb.validation;

import alma.Control.datamodel.meta.amb.Control;
import alma.Control.datamodel.meta.amb.Monitor;

import alma.Control.datamodel.meta.base.BaseFactory;
import alma.Control.datamodel.meta.base.MandCBase;
import alma.Control.datamodel.meta.base.Table;
import alma.Control.datamodel.meta.base.Util;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.amb.MandC}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MandCValidator {
	boolean validate();

	boolean validateRow(String[] value);
	boolean validateSheet(int value);
	boolean validateMcp(MandCBase value);
	boolean validateAmask(String[] value);
	boolean validateAux(BaseFactory value);
	boolean validateToInfoSheet(MandCBase value);

	boolean validateToDataFromMain(Table value);

	boolean validateToMPDataType(Monitor value);

	boolean validateToCPDataType(Control value);

	boolean validateToUtilsToData(Util value);

	boolean validateGetInfoSheet(MandCBase value);
	boolean validateGetDataFromMain(Table value);
	boolean validateIsMPDataType(Monitor value);
	boolean validateIsCPDataType(Control value);
	boolean validateUtilsToData(Util value);
}
