/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import alma.Control.datamodel.meta.base.Table;

import org.eclipse.emf.ecore.resource.Resource;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.ArchiveProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArchivePropertyValidator {
	boolean validate();

	boolean validateRow(String[] value);
	boolean validateSheet(int value);
	boolean validateMp(Resource value);
	boolean validateCp(Resource value);
	boolean validateToColumnsInfoOfArchi(Table value);

	boolean validateGetColumnsInfoOfArchi(Table value);
}
