/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import alma.Control.datamodel.meta.base.ArchiveProperty;
import alma.Control.datamodel.meta.base.ControlPoint;
import alma.Control.datamodel.meta.base.MainBase;
import alma.Control.datamodel.meta.base.MonitorPoint;
import alma.Control.datamodel.meta.base.Table;
import alma.Control.datamodel.meta.base.Util;

import org.eclipse.emf.ecore.resource.ResourceSet;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.DeviceModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeviceModelValidator {
	boolean validate();

	boolean validateDescriptionIndex(int value);
	boolean validateSpreadsheet(String[][][] value);
	boolean validateMain(MainBase value);
	boolean validateNotes(ResourceSet value);
	boolean validateMonitorPoints(ResourceSet value);
	boolean validateControlPoints(ResourceSet value);
	boolean validateArchiveProperties(ResourceSet value);
	boolean validateDeviceName(String value);
	boolean validateBusType(String value);
	boolean validateDeviceDir(String value);
	boolean validateCodegenDir(String value);
	boolean validateSpreadsheetDir(String value);
	boolean validateGeneratedDir(String value);
	boolean validateMonitorDBOnly(boolean value);
	boolean validateGenerateAlt(boolean value);
	boolean validateToArchiveIndex(Table value);

	boolean validateToContPoints(ControlPoint value);

	boolean validateToMoniPoints(MonitorPoint value);

	boolean validateToEndOfGeneration(Util value);

	boolean validateToArchivProp(ArchiveProperty value);

	boolean validateToInfFromSpread(MainBase value);

	boolean validateGetArchiveIndex(Table value);
	boolean validateGetContPoints(ControlPoint value);
	boolean validateGetMoniPoints(MonitorPoint value);
	boolean validateGetEndOfGeneration(Util value);
	boolean validateGetArchivProp(ArchiveProperty value);
	boolean validateGetInfFromSpread(MainBase value);
}
