/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import alma.Control.datamodel.meta.base.DeviceModel;
import alma.Control.datamodel.meta.base.Table;
import alma.Control.datamodel.meta.base.Util;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.MainBase}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MainBaseValidator {
	boolean validate();

	boolean validateRow(String[] value);
	boolean validateSheet(int value);
	boolean validateToImplement(DeviceModel value);

	boolean validateToConvertInfo(Util value);

	boolean validateToInfoFromSpread(Table value);

	boolean validateImplementTo(DeviceModel value);
	boolean validateConvertInfoTo(Util value);
	boolean validateGetInfoFromSpread(Table value);
}
