/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import alma.Control.datamodel.meta.base.ArchiveProperty;
import alma.Control.datamodel.meta.base.Table;

import org.eclipse.emf.ecore.resource.Resource;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.MonitorPoint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MonitorPointValidator {
	boolean validate();

	boolean validateAux(Resource value);
	boolean validateToInfoFromAPSpread(ArchiveProperty value);

	boolean validateToInfoFromMPSpread(Table value);

	boolean validateGetInfoFromAPSpread(ArchiveProperty value);
	boolean validateGetInfoFromMPSpread(Table value);
}
