/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;


/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.Pair}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PairValidator {
	boolean validate();

	boolean validateContent(String value);
	boolean validateNewString(String value);
}
