/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import alma.Control.datamodel.meta.base.SimpleErrorHandler;

import java.util.ArrayList;

import org.xml.sax.ErrorHandler;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.SpreadsheetValidator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpreadsheetValidatorValidator {
	boolean validate();

	boolean validateSeh(SimpleErrorHandler value);
	boolean validateErrorList(ArrayList value);
	boolean validateSehTmp(ErrorHandler value);
	boolean validateErrorHandler(SimpleErrorHandler value);
}
