/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import java.util.ArrayList;
import java.util.Hashtable;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.Table}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableValidator {
	boolean validate();

	boolean validateDepChar(String value);
	boolean validateCelsiusToKelvin(String value);
	boolean validateSheetNames(ArrayList value);
	boolean validateColNames(ArrayList value);
	boolean validateTagNames(ArrayList value);
	boolean validateToCPP(Hashtable value);
	boolean validateToIDL(Hashtable value);
	boolean validateToIDLSeq(Hashtable value);
	boolean validateToCORBA(Hashtable value);
	boolean validateToCORBASeq(Hashtable value);
	boolean validateToCORBADevIO(Hashtable value);
	boolean validateToBACI(Hashtable value);
	boolean validateToDatabase(Hashtable value);
	boolean validateRawToCPP(Hashtable value);
	boolean validateRawToByteSwapped(Hashtable value);
	boolean validateRawBytes(Hashtable value);
	boolean validateWorldToCPP(Hashtable value);
	boolean validateWorldToIDL(Hashtable value);
	boolean validateWorldToIDLSeq(Hashtable value);
	boolean validateWorldToCORBA(Hashtable value);
	boolean validateWorldToCORBASeq(Hashtable value);
	boolean validateWorldToCORBADevIO(Hashtable value);
	boolean validateWorldToBACI(Hashtable value);
	boolean validateWorldToJava(Hashtable value);
	boolean validateWorldToDatabase(Hashtable value);
}
