/**
 *
 * $Id$
 */
package alma.Control.datamodel.meta.base.validation;

import alma.Control.datamodel.meta.base.BaseFactory;
import alma.Control.datamodel.meta.base.Table;

/**
 * A sample validator interface for {@link alma.Control.datamodel.meta.base.Util}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UtilValidator {
	boolean validate();

	boolean validateNewline(String value);
	boolean validateAux(BaseFactory value);
	boolean validateMaxLength(int value);
	boolean validateMONTH(String[] value);
	boolean validateMONTHalt(String[] value);
	boolean validateToRawBytes(Table value);

	boolean validateGetRawBytes(Table value);
}
